--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/sky-min/Emoji
branches:
- master
projects:
  Emoji:
    path: EmojiPlugin/
    libs:
      - src: sky-min/DataConfig/Data
        version: ^2.2.1
...
